//  GoldenFixture.swift
//  Decoders for Fixtures/golden.json, generated by
//  `priors-research/scripts/make_golden.py` from the ADOpy-validated reference.
//
//  Regenerate with:
//      cd priors-research && PYTHONPATH=. .venv/bin/python scripts/make_golden.py

import Foundation
import XCTest
@testable import PriorsEngine

struct GoldenSummary: Codable {
    let thetaEMean: Double
    let thetaESD: Double
    let thetaIMean: Double
    let thetaISD: Double
    let betaMean: Double
    let betaSD: Double
    let entropy: Double?

    enum CodingKeys: String, CodingKey {
        case thetaEMean = "theta_e_mean"
        case thetaESD = "theta_e_sd"
        case thetaIMean = "theta_i_mean"
        case thetaISD = "theta_i_sd"
        case betaMean = "beta_mean"
        case betaSD = "beta_sd"
        case entropy
    }
}

struct GoldenGrids: Codable {
    let thetaE: [Double]
    let thetaI: [Double]
    let beta: [Double]

    enum CodingKeys: String, CodingKey {
        case thetaE = "theta_e"
        case thetaI = "theta_i"
        case beta
    }
}

struct GoldenStep: Codable {
    let price: Double
    let trait: String
    let engaged: Bool
    let predictedEngageBefore: Double
    let after: GoldenSummary

    enum CodingKeys: String, CodingKey {
        case price, trait, engaged
        case predictedEngageBefore = "predicted_engage_before"
        case after
    }
}

struct GoldenEIGEntry: Codable {
    let prices: [Double]
    let eig: [Double]
}

struct GoldenObservation: Codable {
    let price: Double
    let trait: String
    let engaged: Bool
}

struct GoldenRefit: Codable {
    let observations: [GoldenObservation]
    let full: GoldenSummary
    let situation: GoldenSummary
    let misread: GoldenSummary

    enum CodingKeys: String, CodingKey {
        case observations, full
        case situation = "situation_index2_w0.5"
        case misread = "misread_index2_w0.2"
    }
}

struct GoldenDesign: Codable {
    let slot: Int
    let template: String
    let trait: String
    let price: Double
    let instance: Int
    let skin: String
    let eig: Double
    let priceRule: String
    let curiosityOverride: Bool
    let isRepeatOf: Int?
    let engaged: Bool

    enum CodingKeys: String, CodingKey {
        case slot, template, trait, price, instance, skin, eig, engaged
        case priceRule = "price_rule"
        case curiosityOverride = "curiosity_override"
        case isRepeatOf = "is_repeat_of"
    }
}

struct GoldenADOSession: Codable {
    let designs: [GoldenDesign]
    let final: GoldenSummary
}

struct GoldenRTLaw: Codable {
    let peakMean: Double
    let peakSD: Double
    let sigmaMean: Double
    let rtBaseMean: Double

    enum CodingKeys: String, CodingKey {
        case peakMean = "peak_mean"
        case peakSD = "peak_sd"
        case sigmaMean = "sigma_mean"
        case rtBaseMean = "rt_base_mean"
    }
}

struct GoldenRTStep: Codable {
    let price: Double
    let trait: String
    let engaged: Bool
    let rtMs: Double
    let predictedEngageBefore: Double
    let after: GoldenSummary
    let rtLaw: GoldenRTLaw

    enum CodingKeys: String, CodingKey {
        case price, trait, engaged, after
        case rtMs = "rt_ms"
        case predictedEngageBefore = "predicted_engage_before"
        case rtLaw = "rt_law"
    }
}

struct GoldenNuisanceGrids: Codable {
    let rtBase: [Double]
    let peak: [Double]
    let sigma: [Double]

    enum CodingKeys: String, CodingKey {
        case rtBase = "rt_base"
        case peak, sigma
    }
}

struct GoldenBehavioural: Codable {
    let grids: GoldenNuisanceGrids
    let sequence: [GoldenRTStep]
}

struct GoldenChoiceOnly: Codable {
    let sequence: [GoldenStep]
}

struct GoldenEIG: Codable {
    let afterChoiceOnlySequence: [String: GoldenEIGEntry]
    enum CodingKeys: String, CodingKey {
        case afterChoiceOnlySequence = "after_choice_only_sequence"
    }
}

struct Golden: Codable {
    let grids: GoldenGrids
    let prior: GoldenSummary
    let choiceOnly: GoldenChoiceOnly
    let eig: GoldenEIG
    let refit: GoldenRefit
    let adoSession: GoldenADOSession
    let behavioural: GoldenBehavioural

    enum CodingKeys: String, CodingKey {
        case grids, prior, eig, refit, behavioural
        case choiceOnly = "choice_only"
        case adoSession = "ado_session"
    }

    static func load() throws -> Golden {
        guard let url = Bundle.module.url(forResource: "golden", withExtension: "json",
                                          subdirectory: "Fixtures")
        else {
            throw XCTSkip("golden.json missing — run scripts/make_golden.py in priors-research")
        }
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }
}

extension String {
    var asTrait: Trait { Trait(rawValue: self)! }
}
