"""Generate cross-language golden fixtures for PriorsEngine.

SPEC §5 requires the Swift port to reproduce Python's behaviour. This writes a
JSON fixture consumed by the Swift test suite, so the expected values are
generated from the reference implementation rather than transcribed by hand.

Everything here is deterministic. The ADO section runs with jitter disabled and
a rule-based response (engage iff price < 0.45) so no RNG has to agree across
two languages — only the maths does.

Run: PYTHONPATH=. .venv/bin/python scripts/make_golden.py
"""
from __future__ import annotations

import json
import pathlib

import numpy as np

from priors.ado import SelectionState, candidate_prices, expected_information_gain, select_design
from priors.posterior import Posterior
from priors.rt_posterior import BehaviouralPosterior
from priors.scenarios import TRAIT_SCHEDULE

OUT = pathlib.Path(__file__).resolve().parents[2] / "PriorsEngine" / "Tests" / "PriorsEngineTests" / "Fixtures"


def summarise(p) -> dict:
    me, se = p.mean_sd("theta_e")
    mi, si = p.mean_sd("theta_i")
    bm, bs = p.beta_mean_sd()
    return {
        "theta_e_mean": me, "theta_e_sd": se,
        "theta_i_mean": mi, "theta_i_sd": si,
        "beta_mean": bm, "beta_sd": bs,
    }


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    ref = Posterior()

    fixture: dict = {
        "_comment": "Generated by priors-research/scripts/make_golden.py. Do not hand-edit.",
        "grids": {
            "theta_e": ref.theta_e.tolist(),
            "theta_i": ref.theta_i.tolist(),
            "beta": ref.beta.tolist(),
        },
        "prior": summarise(ref) | {"entropy": ref.entropy()},
    }

    # -- 1. choice-only posterior, step by step ----------------------------
    sequence = [
        (0.30, "theta_e", True), (0.62, "theta_e", False), (0.45, "theta_e", True),
        (0.18, "theta_i", True), (0.55, "theta_i", False), (0.72, "theta_e", False),
        (0.25, "theta_e", True), (0.40, "theta_i", True), (0.85, "theta_e", False),
        (0.05, "theta_e", True), (0.33, "theta_i", False), (0.50, "theta_e", True),
    ]
    p = Posterior()
    steps = []
    for price, trait, engaged in sequence:
        pred = p.predicted_engage(price, trait)      # BEFORE the update (SCHEMA §1)
        p.update(price, trait, engaged)
        steps.append({
            "price": price, "trait": trait, "engaged": engaged,
            "predicted_engage_before": pred,
            "after": summarise(p) | {"entropy": p.entropy()},
        })
    fixture["choice_only"] = {"sequence": steps}

    # -- 2. EIG over the candidate prices, from that posterior -------------
    fixture["eig"] = {
        "after_choice_only_sequence": {
            trait: {
                "prices": candidate_prices(trait).tolist(),
                "eig": expected_information_gain(p, candidate_prices(trait), trait).tolist(),
            }
            for trait in ("theta_e", "theta_i")
        }
    }

    # -- 3. down-weighted refit (SPEC §10) ---------------------------------
    obs = [(pr, tr, en) for pr, tr, en in sequence]
    fixture["refit"] = {
        "observations": [{"price": a, "trait": b, "engaged": c} for a, b, c in obs],
        "full": summarise(Posterior.from_observations(obs)),
        "situation_index2_w0.5": summarise(
            Posterior.from_observations(obs, [0.5 if i == 2 else 1.0 for i in range(len(obs))])),
        "misread_index2_w0.2": summarise(
            Posterior.from_observations(obs, [0.2 if i == 2 else 1.0 for i in range(len(obs))])),
    }

    # -- 4. a full 30-slot ADO session, no jitter, rule-based responses ----
    rng = np.random.default_rng(0)   # unused: jitter is off, no stochastic path
    post, state = Posterior(), SelectionState()
    designs = []
    for slot in range(len(TRAIT_SCHEDULE)):
        d = select_design(post, slot, state, rng, jitter=False)
        engaged = bool(d.price < 0.45)          # deterministic, language-independent
        state.commit(d)
        post.update(d.price, d.trait, engaged)
        designs.append({
            "slot": d.slot, "template": d.template, "trait": d.trait,
            "price": d.price, "instance": d.instance, "skin": d.skin,
            "eig": d.eig, "price_rule": d.price_rule,
            "curiosity_override": d.curiosity_override,
            "is_repeat_of": d.is_repeat_of, "engaged": engaged,
        })
    fixture["ado_session"] = {
        "response_rule": "engaged = price < 0.45",
        "jitter": False,
        "designs": designs,
        "final": summarise(post),
    }

    # -- 5. behavioural posterior (choice + hesitation) --------------------
    b = BehaviouralPosterior()
    rt_seq = [
        (0.30, "theta_e", True, 2100.0), (0.62, "theta_e", False, 4800.0),
        (0.45, "theta_e", True, 6200.0), (0.18, "theta_i", True, 1900.0),
        (0.55, "theta_i", False, 3300.0), (0.72, "theta_e", False, 2400.0),
    ]
    rt_steps = []
    for price, trait, engaged, rt in rt_seq:
        pred = b.predicted_engage(price, trait)
        b.update(price, trait, engaged, rt_ms=rt)
        law = b.rt_law()
        rt_steps.append({
            "price": price, "trait": trait, "engaged": engaged, "rt_ms": rt,
            "predicted_engage_before": pred,
            "after": summarise(b),
            "rt_law": {"peak_mean": law.peak_mean, "peak_sd": law.peak_sd,
                       "sigma_mean": law.sigma_mean, "rt_base_mean": law.rt_base_mean},
        })
    fixture["behavioural"] = {
        "grids": {"rt_base": b.rt_base.tolist(), "peak": b.peak.tolist(),
                  "sigma": b.sigma.tolist()},
        "sequence": rt_steps,
    }

    path = OUT / "golden.json"
    path.write_text(json.dumps(fixture, indent=2))
    print(f"wrote {path}")
    print(f"  choice-only steps : {len(steps)}")
    print(f"  ado designs       : {len(designs)}")
    print(f"  behavioural steps : {len(rt_steps)}")
    print(f"  size              : {path.stat().st_size/1024:.1f} KB")


if __name__ == "__main__":
    main()
