//
//  VillageAssets.swift
//  Priors
//
//  Textures for the top-down village, sliced from `TinyTown.png`.
//
//  Source: Kenney "Tiny Town" 1.1, CC0. Tiles are **16x16 native** and are
//  drawn at 2x, giving the 32pt tiles SPEC §8 asks for. Generated by
//  `scripts/build_assets.py` — regenerate there, never hand-edit the sheet.
//
//  The previous version sliced a hand-pasted atlas on a 32px grid whose content
//  was authored at 16px, so every "tile" grabbed a 2x2 block of unrelated
//  neighbours: `wallStone` rendered a window, `well` rendered a beehive, and a
//  third of the sheet was blank. The index map below is the single place the
//  grid can be wrong, and `VillageAssetsTests` pins it.
//

import SpriteKit
import UIKit

public enum Direction: String, CaseIterable, Sendable {
    case down
    case up
    case left
    case right

    public var vector: CGVector {
        switch self {
        case .down: return CGVector(dx: 0, dy: -1)
        case .up: return CGVector(dx: 0, dy: 1)
        case .left: return CGVector(dx: -1, dy: 0)
        case .right: return CGVector(dx: 1, dy: 0)
        }
    }

    public static func from(vector: CGVector) -> Direction {
        if abs(vector.dx) > abs(vector.dy) {
            return vector.dx >= 0 ? .right : .left
        } else {
            return vector.dy >= 0 ? .up : .down
        }
    }
}

public enum TileType: Int, CaseIterable, Sendable {
    case grass = 0
    case grassVar1
    case grassVar2
    /// Tonal grass, generated by `build_assets.py` from the base tile. Tiny
    /// Town ships one flat green, so a map filled with it reads as a billiard
    /// table no matter how much scatter goes on top.
    case grassShadow
    case grassSunlit
    case grassDry
    case pathCenter
    case pathHorizontal
    case pathVertical
    case water
    case waterEdge
    case tree
    case wallStone
    case wallWood
    case roofRed
    case doorClosed
    case doorOpen
    case window
    case chimney
    case well
    case fence

    /// Index into the Tiny Town sheet, row-major over 12 columns.
    ///
    /// Read off the source sheet, not guessed. 132 and 133 are the generated
    /// water tiles `build_assets.py` appends — Tiny Town has none, and the pond
    /// is what COPY R7 names "the pond".
    var sheetIndex: Int {
        switch self {
        case .grass: return 0
        case .grassVar1: return 1
        case .grassVar2: return 2
        case .grassShadow: return 134
        case .grassSunlit: return 135
        case .grassDry: return 136
        case .pathCenter: return 25
        case .pathHorizontal: return 40
        case .pathVertical: return 41
        case .water: return 132
        case .waterEdge: return 133
        case .tree: return 4
        case .wallStone: return 76
        case .wallWood: return 72
        case .roofRed: return 53
        case .doorClosed: return 85
        case .doorOpen: return 86
        case .window: return 84
        case .chimney: return 51
        case .well: return 125
        case .fence: return 45
        }
    }
}

@MainActor
public final class VillageAssets {
    public static let shared = VillageAssets()

    /// On-screen tile size. Source art is 16px, drawn at 2x.
    public static let tileSize: CGFloat = 32.0
    /// Source pixels per tile in `TinyTown.png`.
    static let sourceTile = 16

    private var tileTextures: [TileType: SKTexture] = [:]
    private var playerFrames: [Direction: [SKTexture]] = [:]
    /// Five faceless hooded villagers, two frames each.
    private var villagerVariants: [[SKTexture]] = []

    public init() {
        loadTiles()
        loadCharacters()
    }

    // MARK: - Tiles

    private func loadTiles() {
        guard let sheet = loadImage(named: "TinyTown")?.cgImage else {
            generateFallbackTileTextures()
            return
        }
        let cols = sheet.width / Self.sourceTile
        for type in TileType.allCases {
            let idx = type.sheetIndex
            let (row, col) = (idx / cols, idx % cols)
            let rect = CGRect(x: col * Self.sourceTile, y: row * Self.sourceTile,
                              width: Self.sourceTile, height: Self.sourceTile)
            if let cropped = sheet.cropping(to: rect) {
                let t = SKTexture(cgImage: cropped)
                t.filteringMode = .nearest      // never smooth pixel art
                tileTextures[type] = t
            }
        }
        if tileTextures.count != TileType.allCases.count {
            generateFallbackTileTextures()
        }
    }

    // MARK: - Characters

    /// `Traveller.png` is 4 columns x 4 rows of 16x16:
    ///   row 0: player down A/B, player side A/B
    ///   row 1: player up A/B,   villager 1 A/B
    ///   row 2: villager 2 A/B,  villager 3 A/B
    ///   row 3: villager 4 A/B,  villager 5 A/B
    ///
    /// Source is Kenney "Roguelike Characters" (CC0), rows 0-2 column 0 — the
    /// HOODED figures, not the human ones. Every character is that same
    /// silhouette in a different hood colour, so SPEC §8's "Villagers have no
    /// faces" holds by construction rather than by erasing pixels off a face
    /// that was drawn. The human sprites used before had hair, skin, and in
    /// the player's case an open mouth that was never stripped at all.
    ///
    /// The pack has no walk cycle, so the step is a derived one-pixel bob;
    /// left is the side pair mirrored by `CharacterNode`. There is no back
    /// view to draw: a hood reads the same from behind, which is the honest
    /// consequence of facelessness rather than a shortcut.
    ///
    /// Characters do **not** come from the Tiny Town tile sheet. Tiny Town is a
    /// buildings-and-props pack containing no people; its tile 104, briefly
    /// shipped here as the player, is a well.
    private func loadCharacters() {
        guard let sheet = loadImage(named: "Traveller")?.cgImage else {
            generateFallbackCharacterTextures()
            return
        }
        func frame(_ col: Int, _ row: Int) -> SKTexture? {
            let rect = CGRect(x: col * Self.sourceTile, y: row * Self.sourceTile,
                              width: Self.sourceTile, height: Self.sourceTile)
            guard let c = sheet.cropping(to: rect) else { return nil }
            let t = SKTexture(cgImage: c)
            t.filteringMode = .nearest
            return t
        }
        guard let downA = frame(0, 0), let downB = frame(1, 0),
              let sideA = frame(2, 0), let sideB = frame(3, 0),
              let upA = frame(0, 1), let upB = frame(1, 1),
              let v1a = frame(2, 1), let v1b = frame(3, 1),
              let v2a = frame(0, 2), let v2b = frame(1, 2),
              let v3a = frame(2, 2), let v3b = frame(3, 2),
              let v4a = frame(0, 3), let v4b = frame(1, 3),
              let v5a = frame(2, 3), let v5b = frame(3, 3)
        else {
            generateFallbackCharacterTextures()
            return
        }
        playerFrames[.down] = [downA, downB]
        playerFrames[.up] = [upA, upB]
        playerFrames[.right] = [sideA, sideB]
        playerFrames[.left] = [sideA, sideB]     // drawn flipped by CharacterNode
        villagerVariants = [[v1a, v1b], [v2a, v2b], [v3a, v3b], [v4a, v4b], [v5a, v5b]]
    }

    private func loadImage(named name: String) -> UIImage? {
        if let img = UIImage(named: name) { return img }
        if let path = Bundle.main.path(forResource: name, ofType: "png"),
           let img = UIImage(contentsOfFile: path) { return img }
        return nil
    }

    // MARK: - Fallbacks
    //
    // Flat colours, used only when the sheet is missing from the bundle. They
    // keep the village navigable in that case; they are not a look anyone ships.

    private func generateFallbackCharacterTextures() {
        for dir in Direction.allCases {
            playerFrames[dir] = [fallbackTexture(color: .white), fallbackTexture(color: .white)]
        }
        villagerVariants = [[fallbackTexture(color: .lightGray), fallbackTexture(color: .lightGray)]]
    }

    private func generateFallbackTileTextures() {
        for type in TileType.allCases {
            let color: UIColor
            switch type {
            case .grass, .grassVar1, .grassVar2: color = .init(red: 0.42, green: 0.75, blue: 0.35, alpha: 1)
            case .grassShadow: color = .init(red: 0.36, green: 0.64, blue: 0.30, alpha: 1)
            case .grassSunlit: color = .init(red: 0.48, green: 0.82, blue: 0.40, alpha: 1)
            case .grassDry: color = .init(red: 0.46, green: 0.70, blue: 0.32, alpha: 1)
            case .pathCenter, .pathHorizontal, .pathVertical: color = .init(red: 0.90, green: 0.72, blue: 0.52, alpha: 1)
            case .water, .waterEdge: color = .init(red: 0.0, green: 0.60, blue: 0.86, alpha: 1)
            case .tree: color = .init(red: 0.20, green: 0.50, blue: 0.25, alpha: 1)
            case .wallStone: color = .init(red: 0.66, green: 0.70, blue: 0.75, alpha: 1)
            case .wallWood: color = .init(red: 0.74, green: 0.51, blue: 0.33, alpha: 1)
            case .roofRed: color = .init(red: 0.80, green: 0.35, blue: 0.28, alpha: 1)
            case .doorClosed, .doorOpen: color = .init(red: 0.40, green: 0.25, blue: 0.16, alpha: 1)
            case .window: color = .init(red: 0.78, green: 0.84, blue: 0.90, alpha: 1)
            case .chimney: color = .init(red: 0.45, green: 0.45, blue: 0.48, alpha: 1)
            case .well: color = .init(red: 0.52, green: 0.52, blue: 0.56, alpha: 1)
            case .fence: color = .init(red: 0.62, green: 0.45, blue: 0.30, alpha: 1)
            }
            tileTextures[type] = fallbackTexture(color: color)
        }
    }

    private func fallbackTexture(color: UIColor) -> SKTexture {
        let size = CGSize(width: 16, height: 16)
        let image = UIGraphicsImageRenderer(size: size).image { ctx in
            color.setFill()
            ctx.fill(CGRect(origin: .zero, size: size))
        }
        let t = SKTexture(image: image)
        t.filteringMode = .nearest
        return t
    }

    // MARK: - Accessors

    public func playerWalkCycle(direction: Direction) -> [SKTexture] {
        playerFrames[direction] ?? [fallbackTexture(color: .white)]
    }

    public func playerIdleTexture(direction: Direction) -> SKTexture {
        playerFrames[direction]?.first ?? fallbackTexture(color: .white)
    }

    public var villagerVariantCount: Int { max(villagerVariants.count, 1) }

    /// Villagers come in three appearances so the village does not read as one
    /// person duplicated. All three are faceless (SPEC §8).
    public func npcWalkCycle(variant: Int) -> [SKTexture] {
        guard !villagerVariants.isEmpty else { return [fallbackTexture(color: .lightGray)] }
        return villagerVariants[abs(variant) % villagerVariants.count]
    }

    public func npcIdleTexture(variant: Int) -> SKTexture {
        npcWalkCycle(variant: variant).first ?? fallbackTexture(color: .lightGray)
    }

    public func npcWalkCycle(direction: Direction) -> [SKTexture] { npcWalkCycle(variant: 0) }

    public func npcIdleTexture(direction: Direction) -> SKTexture { npcIdleTexture(variant: 0) }

    public func texture(for tileType: TileType) -> SKTexture {
        tileTextures[tileType] ?? fallbackTexture(color: .gray)
    }
}
